version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: bike_booking_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - bike_booking_net

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server-prod
    container_name: bike_booking_server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/bike-booking-qr
      - JWT_SECRET=dev_jwt_secret_key_antigravity_bike_booking_2026
      - JWT_EXPIRE=1d
      - JWT_REFRESH_SECRET=dev_jwt_refresh_secret_key_antigravity_bike_booking_2026
      - JWT_REFRESH_EXPIRE=7d
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - bike_booking_net

  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: client-prod
    container_name: bike_booking_client
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - bike_booking_net

volumes:
  mongo_data:

networks:
  bike_booking_net:
    driver: bridge
